version: '3.9'
services:
  #mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ICC_cunori.2022
      MYSQL_DATABASE: wordpress
      MYSQL_USER:  admin_iic
      MYSQL_PASSWORD: admin
    volumes:
      -  ./mysql:/var/lib/mysql
      
  #PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    
  #WORDPRESS
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: admin_iic
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./html:/var/www/html
